const query = `CREATE TABLE IF NOT EXISTS user (
    id VARCHAR(255) PRIMARY KEY,
    username VARCHAR(255) UNiQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);`

export default query;